service: aws-node-http-api-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-1

functions:
  getTrades:
    handler: getTrades.getTrades
    events:
      - httpApi:
          path: /
          method: get
  getTradesFromPair:
    handler: getTradesFromPair.getTradesFromPair
    events:
      - httpApi:
          path: /{pair}
          method: get
